spring:
  datasource:
    url: ${APP_SPRING_DATASOURCE_URL}
    username: ${APP_SPRING_DATASOURCE_USERNAME}
    password: ${APP_SPRING_DATASOURCE_PASSWORD}
  jpa:
    database: "mysql"
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
server:
  servlet:
    encoding:
      force: true

asm-gameday:
  baseUrl: ${ASM_GAMEDAY_BASE_URL}